#ifndef _ENUM
#define _ENUM

enum tokenType{ADD, ADDU, ADDIU, SUB, SUBU, MUL, MULU, DIV,
  DIVU, XOR, XORU, NEG, NEGU, REM, REMU, LI, SEQ, SGE,
  SGT, SLE, SLT, SNE, B, BEQ, BNE, BGE, BLE, BGT, BLT,
  BEQZ, BNEZ, BLEZ, BGEZ, BGTZ, BLTZ, J, JR, JAL, JALR, LA, 
  LB, LH, LW, SB, SH, SW, MOVE, MFHI, MFLO, NOP, SYSCALL, NONE};

#endif
